#!/usr/bin/env python3
"""Provision OnCUE E2E test credentials (Supabase cloud or local Postgres).

Writes/updates `.env.test` with hosted desktop config + LiteLLM virtual key.
"""
from __future__ import annotations

import json
import os
import sys
import uuid
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
ENV_TEST = ROOT / ".env.test"
ENV_EXAMPLE = ROOT / ".env.test.example"

DEFAULT_USER_ID = "00000000-0000-4000-8000-000000000001"
DEFAULT_EMAIL = "oncue-e2e-test@example.com"
DEFAULT_PASSWORD = "OnCUE-E2E-Test-Only-2026!"


def load_env_file(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip().split("#")[0].strip()
    return out


def save_env_test(values: dict[str, str]) -> None:
    lines = [
        "# Auto-generated by scripts/provision_test_user.py — E2E test only.",
        "# Do not use in production.",
        "",
    ]
    order = [
        "ONCUE_TEST_USER_ID",
        "ONCUE_TEST_EMAIL",
        "ONCUE_TEST_PASSWORD",
        "ONCUE_BACKEND_URL",
        "ONCUE_WEB_URL",
        "ONCUE_RAG_URL",
        "ONCUE_TOKEN",
        "HOSTED_MODEL",
        "LITELLM_URL",
        "LITELLM_MASTER_KEY",
        "NEXT_PUBLIC_SUPABASE_URL",
        "NEXT_PUBLIC_SUPABASE_ANON_KEY",
        "SUPABASE_SERVICE_ROLE_KEY",
        "EMBED_SECRET",
        "E2E_DATABASE_URL",
        "E2E_USAGE_API_PORT",
    ]
    seen: set[str] = set()
    for key in order:
        if key in values:
            lines.append(f"{key}={values[key]}")
            seen.add(key)
    for key, val in sorted(values.items()):
        if key not in seen:
            lines.append(f"{key}={val}")
    ENV_TEST.write_text("\n".join(lines) + "\n")
    print(f"Wrote {ENV_TEST}")


def mint_litellm_key(user_id: str, tier: str, litellm_url: str, master_key: str) -> str:
    payload = json.dumps({
        "models": ["oncue-groq", "oncue-default"],
        "max_budget": 1,
        "budget_duration": "30d",
        "metadata": {"user_id": user_id},
    }).encode()
    req = Request(
        f"{litellm_url.rstrip('/')}/key/generate",
        data=payload,
        method="POST",
        headers={
            "Authorization": f"Bearer {master_key}",
            "Content-Type": "application/json",
        },
    )
    with urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read().decode())
    key = data.get("key")
    if not key:
        raise RuntimeError(f"LiteLLM key/generate failed: {data}")
    return key


def provision_supabase(env: dict[str, str], user_id: str, email: str, password: str) -> str:
    """Create or reset test user in Supabase; return user_id."""
    url = env.get("NEXT_PUBLIC_SUPABASE_URL", "").rstrip("/")
    service_key = env.get("SUPABASE_SERVICE_ROLE_KEY", "")
    if not url or "YOUR-PROJECT" in url or not service_key or "your-" in service_key:
        raise RuntimeError("Supabase credentials not configured")

    headers = {
        "apikey": service_key,
        "Authorization": f"Bearer {service_key}",
        "Content-Type": "application/json",
    }

    # Try create user; on conflict, fetch existing by email.
    create_body = json.dumps({
        "email": email,
        "password": password,
        "email_confirm": True,
        "user_metadata": {"e2e_test": True},
    }).encode()
    req = Request(f"{url}/auth/v1/admin/users", data=create_body, method="POST", headers=headers)
    try:
        with urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode())
        user_id = data["id"]
        print(f"Created Supabase test user {email} ({user_id})")
    except Exception as e:
        if "already" not in str(e).lower() and "422" not in str(e):
            raise
        # List users and find by email
        list_req = Request(f"{url}/auth/v1/admin/users", headers=headers)
        with urlopen(list_req, timeout=15) as resp:
            users = json.loads(resp.read().decode()).get("users", [])
        match = next((u for u in users if u.get("email") == email), None)
        if not match:
            raise RuntimeError(f"Could not create or find test user: {e}") from e
        user_id = match["id"]
        print(f"Reusing Supabase test user {email} ({user_id})")

    # Reset profile trial state via REST (profiles table)
    profile_body = json.dumps({
        "id": user_id,
        "tier": "free",
        "session_count": 0,
        "trial_used": False,
    }).encode()
    upsert_headers = {**headers, "Prefer": "resolution=merge-duplicates"}
    prof_req = Request(
        f"{url}/rest/v1/profiles",
        data=profile_body,
        method="POST",
        headers=upsert_headers,
    )
    try:
        urlopen(prof_req, timeout=15).close()
    except Exception:
        patch_body = json.dumps({
            "tier": "free",
            "session_count": 0,
            "trial_used": False,
        }).encode()
        patch_req = Request(
            f"{url}/rest/v1/profiles?id=eq.{user_id}",
            data=patch_body,
            method="PATCH",
            headers=headers,
        )
        urlopen(patch_req, timeout=15).close()

    # Clear usage ledger for clean trial
    del_req = Request(
        f"{url}/rest/v1/usage_ledger?user_id=eq.{user_id}",
        method="DELETE",
        headers=headers,
    )
    try:
        urlopen(del_req, timeout=15).close()
    except Exception:
        pass

    print("Reset Supabase profile trial state")
    return user_id


def provision_local(env: dict[str, str], user_id: str, email: str) -> None:
    import psycopg2

    db_url = env.get("E2E_DATABASE_URL", "postgresql://oncue:oncue-e2e-local@localhost/oncue_e2e")
    schema = (ROOT / "scripts/e2e/schema.sql").read_text()
    with psycopg2.connect(db_url) as conn, conn.cursor() as cur:
        cur.execute(schema)
        cur.execute("delete from usage_ledger where user_id = %s", (user_id,))
        cur.execute(
            """insert into profiles (id, tier, session_count, trial_used, persona)
               values (%s, 'free', 0, false, %s)
               on conflict (id) do update set
                 tier = 'free', session_count = 0, trial_used = false,
                 litellm_key = null""",
            (user_id, f"E2E test user ({email})"),
        )
        conn.commit()
    print(f"Provisioned local E2E profile for {user_id}")


def main() -> int:
    base = load_env_file(ENV_EXAMPLE)
    if ENV_TEST.exists():
        base.update(load_env_file(ENV_TEST))

    user_id = base.get("ONCUE_TEST_USER_ID", DEFAULT_USER_ID)
    email = base.get("ONCUE_TEST_EMAIL", DEFAULT_EMAIL)
    password = base.get("ONCUE_TEST_PASSWORD", DEFAULT_PASSWORD)
    litellm_url = base.get("LITELLM_URL", "http://localhost:4000")
    master_key = base.get("LITELLM_MASTER_KEY", "sk-master-oncue-e2e-test")

    try:
        user_id = provision_supabase(base, user_id, email, password)
    except RuntimeError as exc:
        print(f"Supabase mode skipped: {exc}")
        provision_local(base, user_id, email)

    print("Minting LiteLLM virtual key...")
    key = mint_litellm_key(user_id, "free", litellm_url, master_key)

    # Store key in profile
    try:
        import psycopg2

        db_url = base.get("E2E_DATABASE_URL", "postgresql://oncue@localhost/oncue_e2e")
        with psycopg2.connect(db_url) as conn, conn.cursor() as cur:
            cur.execute("update profiles set litellm_key = %s where id = %s", (key, user_id))
            conn.commit()
    except Exception:
        # Supabase-only path: update via REST
        url = base.get("NEXT_PUBLIC_SUPABASE_URL", "").rstrip("/")
        service_key = base.get("SUPABASE_SERVICE_ROLE_KEY", "")
        if url and service_key and "YOUR-PROJECT" not in url:
            patch = json.dumps({"litellm_key": key}).encode()
            req = Request(
                f"{url}/rest/v1/profiles?id=eq.{user_id}",
                data=patch,
                method="PATCH",
                headers={
                    "apikey": service_key,
                    "Authorization": f"Bearer {service_key}",
                    "Content-Type": "application/json",
                },
            )
            urlopen(req, timeout=15).close()

    web_url = base.get("ONCUE_WEB_URL", "http://localhost:3001")
    rag_url = base.get("ONCUE_RAG_URL", f"{web_url.rstrip('/')}/mock/rag")
    backend_url = base.get("ONCUE_BACKEND_URL", f"{litellm_url.rstrip('/')}/v1")

    base.update({
        "ONCUE_TEST_USER_ID": user_id,
        "ONCUE_TEST_EMAIL": email,
        "ONCUE_TEST_PASSWORD": password,
        "ONCUE_TOKEN": key,
        "ONCUE_WEB_URL": web_url,
        "ONCUE_RAG_URL": rag_url,
        "ONCUE_BACKEND_URL": backend_url,
        "HOSTED_MODEL": base.get("HOSTED_MODEL", "oncue-default"),
    })
    save_env_test(base)

    deep_link = (
        f"oncue://connect?{urlencode({'token': key, 'web': web_url, 'rag': rag_url, 'backend': backend_url})}"
    )
    print("\n--- E2E test credentials ready ---")
    print(f"Email:    {email}")
    print(f"Password: {password}")
    print(f"Key:      {key[:12]}...")
    print(f"Deep link: {deep_link[:80]}...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
